import CatalogItem from '../models/CatalogItem.js';

export const CATALOG_CATEGORY_DEFINITIONS = [
  {
    name: 'Wall Lamp',
    slug: 'wall-lamp',
    categoryKey: 'wall',
    icon: '💡',
    tag: 'Architectural Sconces',
    description: 'Bi-directional wall grazers, fluted glass sconces, and indirect perimeter illumination for corridors, foyers, and bedside alcoves.',
    specs: 'LED & E27 • Ra > 95 • 3000K Warm • IP44 Rated',
    image: '/categories/wall-lamp.jpg',
    subcategories: [
      { name: 'Led Wall Lamp', slug: 'led-wall-lamp', image: '/categories/led-wall-lamp.jpg' },
      { name: 'E27 Wall Lamp', slug: 'e27-wall-lamp', image: '/categories/e27-wall-lamp.jpg' },
    ],
  },
  {
    name: 'Pendant Lamp',
    slug: 'pendant-lamp',
    categoryKey: 'pendant',
    icon: '🔆',
    tag: 'Sculptural Suspensions',
    description: 'Suspended architectural lighting fixtures, mouth-blown fluted glass, and spun brass pendants for dining islands and reception spaces.',
    specs: 'LED & E27 • Dim-to-Warm • 1,200 - 3,400 lm',
    image: '/categories/pendant-lamp.jpg',
    subcategories: [
      { name: 'Led Hanging Lamp', slug: 'led-hanging-lamp', image: '/categories/led-hanging-lamp.jpg' },
      { name: 'E27 Hanging Lamp', slug: 'e27-hanging-lamp', image: '/categories/e27-hanging-lamp.jpg' },
    ],
  },
  {
    name: 'Chandelier',
    slug: 'chandelier',
    categoryKey: 'chandelier',
    icon: '✨',
    tag: 'Grand Statements',
    description: 'Magnificent multi-tier chandeliers spanning LED, Italian Murano glass, architectural profiles, classic antique, and ceiling fan hybrids.',
    specs: 'K9 Crystal • Precision Metal • Up to 5m Drops',
    image: '/categories/chandelier.jpg',
    subcategories: [
      { name: 'Led Chandelier', slug: 'led-chandelier', image: '/categories/chandelier.jpg' },
      { name: 'E14 Chandelier', slug: 'e14-chandelier', image: '/categories/e14-chandelier.jpg' },
      { name: 'Profile Chandelier', slug: 'profile-chandelier', image: '/categories/profile-chandelier.jpg' },
      { name: 'Glass Chandelier', slug: 'glass-chandelier', image: '/categories/glass-chandelier.jpg' },
      { name: 'Italian Chandelier', slug: 'italian-chandelier', image: '/categories/italian-chandelier.jpg' },
      { name: 'Modern chandelier', slug: 'modern-chandelier', image: '/categories/modern-chandelier.jpg' },
      { name: 'Antic Chandelier', slug: 'antic-chandelier', image: '/categories/antic-chandelier.jpg' },
      { name: 'Fan chandelier', slug: 'fan-chandelier', image: '/categories/fan-chandelier.jpg' },
      { name: 'Celling chandelier', slug: 'ceiling-chandelier', image: '/categories/ceiling-chandelier.jpg' },
    ],
  },
  {
    name: 'Double Height',
    slug: 'double-height',
    categoryKey: 'double-height',
    icon: '🏛️',
    tag: 'High-Ceiling Scale',
    description: 'Bespoke monumental cascade chandeliers and modern sculptural fixtures designed for 18ft+ double-height living rooms, stairwells, and grand foyers.',
    specs: 'Multi-Zone DALI Control • High Lumen • Heavy-Duty Suspension',
    image: '/categories/double-height.jpg',
    subcategories: [
      { name: 'Crystal Chandelier', slug: 'crystal-chandelier', image: '/categories/double-height.jpg' },
      { name: 'Modern Chandelier', slug: 'modern-chandelier-dh', image: '/categories/modern-chandelier-dh.jpg' },
    ],
  },
  {
    name: 'Dining Table Lamp',
    slug: 'dining-table-lamp',
    categoryKey: 'dining',
    icon: '🍽️',
    tag: 'Epicurean Warmth',
    description: 'Curated intimate dining luminaires, cordless rechargeable accent lamps, and low-profile warm illumination tailored for executive dining spaces.',
    specs: '2700K Warm Glow • Cordless Touch Dimming • High CRI > 95',
    image: '/categories/dining-table-lamp.jpg',
    subcategories: [],
  },
  {
    name: 'Outdoor Light',
    slug: 'outdoor-light',
    categoryKey: 'outdoor',
    icon: '🌿',
    tag: 'Weatherproof IP65',
    description: 'IP65-rated gate pillar lanterns and exterior wall grazers engineered with marine-grade aluminum to resist moisture, UV rays, and extreme weather.',
    specs: 'IP65 Rated • Die-Cast Aluminum • Weatherproof Glass',
    image: '/categories/outdoor-light.jpg',
    subcategories: [
      { name: 'Gate Lamp', slug: 'gate-lamp', image: '/categories/outdoor-light.jpg' },
      { name: 'Wall Lamp', slug: 'outdoor-wall-lamp', image: '/hero-outdoor.jpg' },
    ],
  },
  {
    name: 'Table Lamp',
    slug: 'table-lamp',
    categoryKey: 'table',
    icon: '🪔',
    tag: 'Sculptural Desks & Bedside',
    description: 'Designer bedside sconces, ceramic studio lamps, and solid brass task lights bringing focused reading light and atmospheric glow to bedside and console tables.',
    specs: 'Solid Brass & Ceramic • In-Line Dimmer • Fabric Cord',
    image: '/categories/table-lamp.jpg',
    subcategories: [],
  },
  {
    name: 'Floor Lamp',
    slug: 'floor-lamp',
    categoryKey: 'floor',
    icon: '🕯️',
    tag: 'Freestanding Columns & Arcs',
    description: 'Statement arched floor lights, minimal vertical light bars, and mid-century tripod fixtures that define living room seating arrangements.',
    specs: 'Weighted Base • Foot Switch • Telescopic Height',
    image: '/categories/floor-lamp.jpg',
    subcategories: [],
  },
  {
    name: 'LED Filament Bulb',
    slug: 'led-filament-bulb',
    categoryKey: 'filament',
    icon: '💫',
    tag: 'Edison Heritage Glow',
    description: 'Vintage-style Amber and Golden tinted Edison LED filament bulbs with spiral and cross-pattern elements, offering antique warmth with 90% energy savings.',
    specs: 'E27 / E14 Base • 2200K Amber Glow • 15,000h Lifespan',
    image: '/categories/led-filament-bulb.jpg',
    subcategories: [],
  },
  {
    name: 'Spare Part',
    slug: 'spare-part',
    categoryKey: 'spares',
    icon: '🔧',
    tag: 'Hardware & Power Drivers',
    description: 'Heavy-duty multi-port hanging ceiling canopies, suspension wire kits, and precision constant-current LED replacement drivers for ongoing fixture maintenance.',
    specs: 'Universal Fit • 12V/24V/Constant Current • CE Certified',
    image: '/categories/spare-part.jpg',
    subcategories: [
      { name: 'Hanging Base', slug: 'hanging-base', image: '/categories/hanging-base.jpg' },
      { name: 'Spare Driver', slug: 'spare-driver', image: '/categories/spare-driver.jpg' },
    ],
  },
];

export const INITIAL_CATALOG_ITEMS = [
  // ── 1. WALL LAMP ──────────────────────────────────────────
  {
    catalogId: 'LH-CAT-001',
    name: 'LH-WL101 Slim LED Wall Lamp',
    slug: 'lh-wl101-slim-led-wall-lamp',
    sku: 'LH-WL101',
    category: 'wall-lamp',
    subcategory: 'led-wall-lamp',
    categoryName: 'Wall Lamp',
    shortDescription: 'Sleek linear LED wall lamp with brushed gold frame and frosted acrylic diffuser.',
    description: 'The LH-WL101 brings a refined horizontal glow to feature walls, headboards, and corridor niches. Its micro-prismatic acrylic diffuser eliminates hotspots for a smooth, uniform luminous surface.',
    price: 3499,
    originalPrice: 4699,
    images: [{ url: '/categories/led-wall-lamp.jpg', alt: 'LH-WL101 Slim LED Wall Lamp', isCover: true }],
    specifications: {
      dimensions: '600mm x 80mm x 55mm',
      material: 'Extruded Aluminum & Acrylic',
      finish: 'Brushed Champagne Gold',
      wattage: '16W Integrated LED',
      voltage: 'AC 100-240V 50/60Hz',
      colorTemperature: '3000K Warm White',
      ipRating: 'IP20 Indoor',
      installationType: 'Surface Wall Mount',
      beamAngle: '120° Diffuse',
      cri: 'Ra > 92',
      luminousFlux: '1450 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 1,
  },
  {
    catalogId: 'LH-CAT-002',
    name: 'LH-WL102 Round Halo LED Wall Light',
    slug: 'lh-wl102-round-led-halo-wall-light',
    sku: 'LH-WL102',
    category: 'wall-lamp',
    subcategory: 'led-wall-lamp',
    categoryName: 'Wall Lamp',
    shortDescription: 'Circular LED wall sconce with indirect 360° perimeter halo glow.',
    description: 'Soft perimeter LED illumination wraps the circular disc, casting a warm halo against the wall. Die-cast aluminum body with a matte finish ensures long-lasting durability.',
    price: 2899,
    originalPrice: 3899,
    images: [{ url: '/categories/wall-lamp.jpg', alt: 'LH-WL102 Round Halo', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 300mm, Depth: 40mm',
      material: 'Die-Cast Aluminum',
      finish: 'Matte Obsidian Black',
      wattage: '12W Integrated LED',
      voltage: 'AC 100-240V',
      colorTemperature: '3000K Warm',
      ipRating: 'IP20 Indoor',
      installationType: 'Flush Wall Mount',
      beamAngle: 'Indirect 360° Halo',
      cri: 'Ra > 90',
      luminousFlux: '1000 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 2,
  },
  {
    catalogId: 'LH-CAT-003',
    name: 'LH-WL201 Brass E27 Swing-Arm Wall Lamp',
    slug: 'lh-wl201-brass-e27-swing-arm-wall-lamp',
    sku: 'LH-WL201',
    category: 'wall-lamp',
    subcategory: 'e27-wall-lamp',
    categoryName: 'Wall Lamp',
    shortDescription: 'Articulating swing-arm E27 wall lamp in hand-brushed satin brass.',
    description: 'Inspired by mid-century European reading lamps, the LH-WL201 features a fully articulated swing arm and a conical shade in satin brass. Compatible with standard E27 bulbs.',
    price: 3199,
    originalPrice: 4299,
    images: [{ url: '/categories/e27-wall-lamp.jpg', alt: 'LH-WL201 Brass E27 Wall Lamp', isCover: true }],
    specifications: {
      dimensions: 'Arm Reach: 450mm, Shade Dia: 180mm',
      material: 'Solid Brass & Steel',
      finish: 'Satin Antique Brass',
      wattage: 'E27 Max 60W',
      voltage: 'AC 220-240V',
      colorTemperature: 'Depends on Bulb',
      ipRating: 'IP20 Indoor',
      installationType: 'Surface Wall Mount',
      beamAngle: 'Adjustable Directional',
      cri: 'Depends on Bulb',
      luminousFlux: 'Depends on Bulb',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 3,
  },

  // ── 2. PENDANT LAMP ───────────────────────────────────────
  {
    catalogId: 'LH-CAT-004',
    name: 'LH-PL101 Cone LED Pendant Lamp',
    slug: 'lh-pl101-cone-led-pendant-lamp',
    sku: 'LH-PL101',
    category: 'pendant-lamp',
    subcategory: 'led-hanging-lamp',
    categoryName: 'Pendant Lamp',
    shortDescription: 'Minimalist matte-black cone LED pendant with focused downlight beam.',
    description: 'The LH-PL101 delivers focused warm illumination directly onto dining surfaces. Its seamless spun-aluminum cone in matte black hides the LED array completely for a clean, glare-free appearance.',
    price: 4299,
    originalPrice: 5799,
    images: [{ url: '/categories/led-hanging-lamp.jpg', alt: 'LH-PL101 Cone Pendant', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 220mm, Height: 320mm, Cable: 1500mm',
      material: 'Spun Aluminum & Optical Acrylic',
      finish: 'Matte Charcoal & Gold Interior',
      wattage: '15W Integrated COB LED',
      voltage: 'AC 100-240V',
      colorTemperature: '3000K Warm White',
      ipRating: 'IP20',
      installationType: 'Ceiling Suspension',
      beamAngle: '45° Focused',
      cri: 'Ra > 93',
      luminousFlux: '1350 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 4,
  },
  {
    catalogId: 'LH-CAT-005',
    name: 'LH-PL201 Fluted Glass E27 Pendant',
    slug: 'lh-pl201-fluted-glass-e27-pendant',
    sku: 'LH-PL201',
    category: 'pendant-lamp',
    subcategory: 'e27-hanging-lamp',
    categoryName: 'Pendant Lamp',
    shortDescription: 'Mouth-blown fluted amber glass pendant with brushed gold hardware.',
    description: 'Handcrafted vertical ribbing in warm amber glass casts gentle linear refraction onto surrounding surfaces. Accommodates standard E27 decorative filament bulbs.',
    price: 3699,
    originalPrice: 4999,
    images: [{ url: '/categories/e27-hanging-lamp.jpg', alt: 'LH-PL201 Fluted Pendant', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 250mm, Glass Height: 280mm',
      material: 'Mouth-Blown Fluted Glass & Brass',
      finish: 'Warm Amber & Brushed Gold',
      wattage: 'E27 Socket (Max 40W)',
      voltage: 'AC 220-240V',
      colorTemperature: 'Warm Amber Glow',
      ipRating: 'IP20',
      installationType: 'Suspended Cable',
      beamAngle: '360° Ambient',
      cri: 'Ra > 95',
      luminousFlux: '600 - 900 lm',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 5,
  },

  // ── 3. CHANDELIER ─────────────────────────────────────────
  {
    catalogId: 'LH-CAT-006',
    name: 'LH-CH101 Multi-Tier Ring LED Chandelier',
    slug: 'lh-ch101-multi-tier-ring-led-chandelier',
    sku: 'LH-CH101',
    category: 'chandelier',
    subcategory: 'led-chandelier',
    categoryName: 'Chandelier',
    shortDescription: '3-Ring floating orbital LED chandelier with brushed champagne gold finish.',
    description: 'Three concentric circular rings suspended on ultra-fine stainless aircraft cables. Continuous internal silicone diffusers for seamless, 360-degree glare-free illumination.',
    price: 18999,
    originalPrice: 25999,
    images: [{ url: '/categories/chandelier.jpg', alt: 'LH-CH101 Orbital Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Rings: 800mm + 600mm + 400mm Dia',
      material: 'Aviation Aluminum & Optical Silicone',
      finish: 'Brushed Champagne Gold',
      wattage: '85W Integrated LED',
      voltage: 'AC 100-240V (Dimmable)',
      colorTemperature: '3000K / 4000K / 6000K Tri-Color',
      ipRating: 'IP20',
      installationType: 'Adjustable Cable Suspension',
      beamAngle: 'Omnidirectional Ring Glow',
      cri: 'Ra > 95',
      luminousFlux: '6800 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 6,
  },
  {
    catalogId: 'LH-CAT-007',
    name: 'LH-CH201 8-Arm E14 French Candelabra Chandelier',
    slug: 'lh-ch201-8-arm-e14-candelabra-chandelier',
    sku: 'LH-CH201',
    category: 'chandelier',
    subcategory: 'e14-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Classic 8-arm candelabra chandelier in antique brass with crystal bobeches.',
    description: 'Sweeping gracefully curved brass arms crowned by precision-cut crystal saucers. Compatible with E14 candle flame bulbs for a timeless palace aesthetic.',
    price: 14500,
    originalPrice: 19500,
    images: [{ url: '/categories/e14-chandelier.jpg', alt: 'LH-CH201 8-Arm E14 French Candelabra Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 750mm, Body Height: 620mm',
      material: 'Forged Brass & K9 Crystal',
      finish: 'Antique Hand-Rubbed Brass',
      wattage: '8 x E14 (Max 40W each)',
      voltage: 'AC 220-240V',
      colorTemperature: 'Warm Candelabra',
      ipRating: 'IP20',
      installationType: 'Ceiling Chain Suspension',
      beamAngle: '360° Ambient',
      cri: 'Ra > 92',
      luminousFlux: 'Approx 3200 Lumens',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 7,
  },
  {
    catalogId: 'LH-CAT-008',
    name: 'LH-CH301 Linear Architectural Profile Chandelier',
    slug: 'lh-ch301-linear-profile-chandelier',
    sku: 'LH-CH301',
    category: 'chandelier',
    subcategory: 'profile-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Minimalist linear architectural profile fixture with dual-directional light.',
    description: 'Precision extruded matte black profile featuring downward task lighting and upward indirect ceiling wash. Perfect for boardroom tables and contemporary luxury dining.',
    price: 12800,
    originalPrice: 17200,
    images: [{ url: '/categories/profile-chandelier.jpg', alt: 'LH-CH301 Linear Architectural Profile Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Length: 1500mm, Width: 45mm, Height: 75mm',
      material: 'Extruded 6063 Aluminum',
      finish: 'Anodized Matte Jet Black',
      wattage: '48W Up/Down LED',
      voltage: 'AC 100-240V',
      colorTemperature: '3000K / 4000K Neutral',
      ipRating: 'IP20',
      installationType: 'Adjustable Aircraft Cable',
      beamAngle: '100° Down / 120° Up',
      cri: 'Ra > 95',
      luminousFlux: '4600 Lumens',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 8,
  },
  {
    catalogId: 'LH-CAT-009',
    name: 'LH-CH401 Murano Cloud Glass Chandelier',
    slug: 'lh-ch401-murano-cloud-glass-chandelier',
    sku: 'LH-CH401',
    category: 'chandelier',
    subcategory: 'glass-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Cluster of 18 hand-blown frosted bubble glass spheres with warm ambient glow.',
    description: 'Organic clustered formation of frosted and clear glass globes suspended at staggered elevations. Creates a floating luminous cloud centerpiece.',
    price: 24500,
    originalPrice: 32999,
    images: [{ url: '/categories/glass-chandelier.jpg', alt: 'LH-CH401 Murano Cloud Glass Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Cluster Span: 900mm, Max Drop: 1800mm',
      material: 'Blown Borosilicate Glass & Brass',
      finish: 'Frosted Opal & Brushed Gold',
      wattage: '18 x G9 LED 4W (72W Total)',
      voltage: 'AC 220-240V',
      colorTemperature: '2700K Warm Gold',
      ipRating: 'IP20',
      installationType: 'Ceiling Rose Canopy',
      beamAngle: '360° Omnidirectional',
      cri: 'Ra > 92',
      luminousFlux: '5400 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 9,
  },
  {
    catalogId: 'LH-CAT-010',
    name: 'LH-CH501 Venetian Filigree Italian Chandelier',
    slug: 'lh-ch501-venetian-filigree-italian-chandelier',
    sku: 'LH-CH501',
    category: 'chandelier',
    subcategory: 'italian-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Authentic Italian style chandelier with hand-shaped crystal scrollwork.',
    description: 'Master artisan crafted Italian silhouette with intricate filigree arms, hanging crystal prisms, and amber glass flourishes.',
    price: 32000,
    originalPrice: 42000,
    images: [{ url: '/categories/italian-chandelier.jpg', alt: 'LH-CH501 Venetian Filigree Italian Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 880mm, Height: 780mm',
      material: 'Italian Crystal & Gilded Brass',
      finish: 'Venetian Gold & Clear Crystal',
      wattage: '12 x E14 LED 5W',
      voltage: 'AC 220-240V',
      colorTemperature: '2700K Warm White',
      ipRating: 'IP20',
      installationType: 'Heavy-Duty Ceiling Hook',
      beamAngle: '360° Prismatic Dispersion',
      cri: 'Ra > 97',
      luminousFlux: '6200 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 10,
  },
  {
    catalogId: 'LH-CAT-011',
    name: 'LH-CH601 Sputnik Brass Geometric Modern Chandelier',
    slug: 'lh-ch601-sputnik-brass-modern-chandelier',
    sku: 'LH-CH601',
    category: 'chandelier',
    subcategory: 'modern-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Mid-century modern radial sputnik chandelier with multi-directional brass rods.',
    description: 'Dynamic radial design extending outward from a central orb with 12 intersecting arms tipped with exposed filament globes or frosted diffusers.',
    price: 11500,
    originalPrice: 15500,
    images: [{ url: '/categories/modern-chandelier.jpg', alt: 'LH-CH601 Sputnik Brass Geometric Modern Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 820mm, Drop: 600mm',
      material: 'Seamless Brass Alloy',
      finish: 'Electroplated Brushed Brass',
      wattage: '12 x E27 / G9 Compatible',
      voltage: 'AC 100-240V',
      colorTemperature: '3000K Warm',
      ipRating: 'IP20',
      installationType: 'Rod Ceiling Mount',
      beamAngle: '360° Radial Array',
      cri: 'Ra > 90',
      luminousFlux: '4200 Lumens',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 11,
  },
  {
    catalogId: 'LH-CAT-012',
    name: 'LH-CH701 Heritage Wrought Iron Antic Chandelier',
    slug: 'lh-ch701-heritage-wrought-iron-antic-chandelier',
    sku: 'LH-CH701',
    category: 'chandelier',
    subcategory: 'antic-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Rustic antique black wrought iron chandelier with distressed brass candle cups.',
    description: 'Forged iron bands sculpted into an open armillary sphere, encasing a multi-tiered candelabra cluster for historical and industrial heritage estates.',
    price: 15800,
    originalPrice: 21000,
    images: [{ url: '/categories/antic-chandelier.jpg', alt: 'LH-CH701 Heritage Wrought Iron Antic Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 700mm, Height: 750mm',
      material: 'Hand-Forged Wrought Iron & Solid Brass',
      finish: 'Distressed Antique Bronze',
      wattage: '6 x E14 Candelabra',
      voltage: 'AC 220-240V',
      colorTemperature: '2200K - 2700K Warm',
      ipRating: 'IP20',
      installationType: 'Heavy Iron Link Chain',
      beamAngle: '360° Open Beam',
      cri: 'Ra > 90',
      luminousFlux: '2800 Lumens',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 12,
  },
  {
    catalogId: 'LH-CAT-013',
    name: 'LH-CH801 Retractable Blade LED Fan Chandelier',
    slug: 'lh-ch801-retractable-blade-fan-chandelier',
    sku: 'LH-CH801',
    category: 'chandelier',
    subcategory: 'fan-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Fandelier with invisible retractable acrylic blades, crystal ring, and remote control.',
    description: 'Combines the cooling comfort of a whisper-quiet DC motor ceiling fan with the visual grandeur of a crystal LED chandelier. Blades automatically retract out of sight when fan is turned off.',
    price: 16999,
    originalPrice: 22999,
    images: [{ url: '/categories/fan-chandelier.jpg', alt: 'LH-CH801 Retractable Blade LED Fan Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Open: 1060mm (42"), Closed: 500mm',
      material: 'Clear Acrylic Blades, K9 Crystal, Steel',
      finish: 'French Gold & Prismatic Crystal',
      wattage: 'LED 36W + DC Motor 35W',
      voltage: 'AC 220-240V 50Hz',
      colorTemperature: 'Tri-Color (3000K/4000K/6500K)',
      ipRating: 'IP20',
      installationType: 'Dual Downrod Mount',
      beamAngle: 'Downlight Graze + Crystal Halo',
      cri: 'Ra > 90',
      luminousFlux: '3200 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 13,
  },
  {
    catalogId: 'LH-CAT-014',
    name: 'LH-CH901 Flush Mount Crystal Ceiling Chandelier',
    slug: 'lh-ch901-flush-mount-crystal-ceiling-chandelier',
    sku: 'LH-CH901',
    category: 'chandelier',
    subcategory: 'ceiling-chandelier',
    categoryName: 'Chandelier',
    shortDescription: 'Low-profile flush ceiling chandelier for 9ft-10ft standard height ceilings.',
    description: 'Specifically engineered for apartments and standard-height ceilings where drop chains are impractical. Dense tiers of cascading faceted crystal droplets.',
    price: 9999,
    originalPrice: 13499,
    images: [{ url: '/categories/ceiling-chandelier.jpg', alt: 'LH-CH901 Flush Mount Crystal Ceiling Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 500mm, Total Depth: 220mm',
      material: 'Mirror Stainless Steel Base & K9 Crystal',
      finish: 'Mirror Chrome & Clear Crystal',
      wattage: '40W Integrated LED',
      voltage: 'AC 100-240V',
      colorTemperature: '3000K Warm White',
      ipRating: 'IP20',
      installationType: 'Direct Flush Ceiling Mount',
      beamAngle: 'Wide Downward Dispersion',
      cri: 'Ra > 92',
      luminousFlux: '3600 Lumens',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 14,
  },

  // ── 4. DOUBLE HEIGHT ──────────────────────────────────────
  {
    catalogId: 'LH-CAT-015',
    name: 'LH-DH101 Grand Crystal Cascade Double Height Chandelier',
    slug: 'lh-dh101-grand-crystal-cascade-double-height-chandelier',
    sku: 'LH-DH101',
    category: 'double-height',
    subcategory: 'crystal-chandelier',
    categoryName: 'Double Height',
    shortDescription: '10-Foot cascading helical crystal chandelier for double-height foyers and villas.',
    description: 'Dramatic multi-tier cascading spiral of over 1,200 precision cut K9 crystals engineered for 18ft+ vertical voids. Celestial prismatic spectacle.',
    price: 48999,
    originalPrice: 65000,
    images: [{ url: '/categories/double-height.jpg', alt: 'LH-DH101 Grand Crystal Cascade Double Height Chandelier', isCover: true }],
    specifications: {
      dimensions: 'Base Diameter: 800mm, Suspension Drop: 3000mm (10 Feet)',
      material: 'High-Purity K9 Crystal & Heavy-Gauge Stainless Steel',
      finish: 'Mirror Polished Gold Canopy',
      wattage: '120W High-Lumen Integrated LED',
      voltage: 'AC 100-240V (Remote Dimmable)',
      colorTemperature: '3000K Warm Gold',
      ipRating: 'IP20',
      installationType: 'Reinforced Concrete Ceiling Anchor',
      beamAngle: 'Volumetric Downward Cascade',
      cri: 'Ra > 98',
      luminousFlux: '11,000 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 15,
  },
  {
    catalogId: 'LH-CAT-016',
    name: 'LH-DH201 Modern Staggered Geometric Rings Double Height',
    slug: 'lh-dh201-modern-staggered-rings-double-height',
    sku: 'LH-DH201',
    category: 'double-height',
    subcategory: 'modern-chandelier-dh',
    categoryName: 'Double Height',
    shortDescription: '5-Ring architectural suspended chandelier with 4-meter adjustable drop cables.',
    description: 'Five monumental interlocking oval rings suspended on independent cables to create custom geometric silhouettes inside high-ceiling luxury atriums.',
    price: 42000,
    originalPrice: 56000,
    images: [{ url: '/categories/modern-chandelier-dh.jpg', alt: 'LH-DH201 Modern Staggered Geometric Rings Double Height', isCover: true }],
    specifications: {
      dimensions: 'Largest Ring: 1200mm Dia, Drop: Up to 4000mm',
      material: 'Extruded Structural Aluminum & Optical Silicone',
      finish: 'Brushed Champagne Bronze',
      wattage: '140W Integrated Driver',
      voltage: 'AC 100-240V DALI / 0-10V Dimming',
      colorTemperature: '3000K Warm White',
      ipRating: 'IP20',
      installationType: 'Heavy-Duty Reinforced Suspension',
      beamAngle: 'Continuous 360° Ring Wash',
      cri: 'Ra > 95',
      luminousFlux: '12,500 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 16,
  },

  // ── 5. DINING TABLE LAMP ──────────────────────────────────
  {
    catalogId: 'LH-CAT-017',
    name: 'LH-DT101 Brushed Gold Rechargeable Dining Table Lamp',
    slug: 'lh-dt101-brushed-gold-dining-table-lamp',
    sku: 'LH-DT101',
    category: 'dining-table-lamp',
    subcategory: '',
    categoryName: 'Dining Table Lamp',
    shortDescription: 'Cordless rechargeable tabletop lamp with touch step-dimming for dining spaces.',
    description: 'Designed to elevate dining ambiance without unsightly cables across the table. Solid aluminum stem with a downward anti-glare optical head.',
    price: 2499,
    originalPrice: 3499,
    images: [{ url: '/categories/dining-table-lamp.jpg', alt: 'LH-DT101 Brushed Gold Rechargeable Dining Table Lamp', isCover: true }],
    specifications: {
      dimensions: 'Base Dia: 100mm, Height: 350mm, Top Dia: 110mm',
      material: 'Machined Aluminum Alloy',
      finish: 'Electroplated Brushed Gold',
      wattage: '3.5W Warm LED (5200mAh Lithium Battery)',
      voltage: 'USB-C 5V Fast Charge',
      colorTemperature: '2700K Warm Gold',
      ipRating: 'IP54 Splashproof',
      installationType: 'Portable Freestanding',
      beamAngle: 'Downward Anti-Glare Conical Wash',
      cri: 'Ra > 96',
      luminousFlux: '320 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 17,
  },

  // ── 6. OUTDOOR LIGHT ──────────────────────────────────────
  {
    catalogId: 'LH-CAT-018',
    name: 'LH-OD101 Heritage Pillar Gate Lamp IP65',
    slug: 'lh-od101-heritage-pillar-gate-lamp',
    sku: 'LH-OD101',
    category: 'outdoor-light',
    subcategory: 'gate-lamp',
    categoryName: 'Outdoor Light',
    shortDescription: 'Architectural outdoor pillar gate lantern in matte black with seeded glass.',
    description: 'Forged from corrosion-resistant die-cast aluminum with tempered water-resistant glass. Mounts securely onto entrance boundary pillars and gate posts.',
    price: 4199,
    originalPrice: 5699,
    images: [{ url: '/categories/outdoor-light.jpg', alt: 'LH-OD101 Heritage Pillar Gate Lamp IP65', isCover: true }],
    specifications: {
      dimensions: 'Base: 250mm x 250mm, Height: 480mm',
      material: 'Die-Cast Aluminum & Seeded Weatherproof Glass',
      finish: 'UV-Resistant Powder Coat Matte Black',
      wattage: 'E27 Socket (Max 60W)',
      voltage: 'AC 100-240V',
      colorTemperature: '3000K Warm Amber',
      ipRating: 'IP65 Weatherproof',
      installationType: 'Pillar / Pedestal Base Mount',
      beamAngle: '360° Perimeter Wash',
      cri: 'Ra > 90',
      luminousFlux: '1200 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 18,
  },
  {
    catalogId: 'LH-CAT-019',
    name: 'LH-OD201 Bi-Directional IP65 Outdoor Wall Lamp',
    slug: 'lh-od201-bi-directional-outdoor-wall-lamp',
    sku: 'LH-OD201',
    category: 'outdoor-light',
    subcategory: 'outdoor-wall-lamp',
    categoryName: 'Outdoor Light',
    shortDescription: 'IP65 up & down outdoor wall grazer with adjustable optical beam shutters.',
    description: 'Dual-side architectural exterior sconce with internal mechanical shutters to independently calibrate upper and lower beam spread from 0° to 120°.',
    price: 2999,
    originalPrice: 3999,
    images: [{ url: '/hero-outdoor.jpg', alt: 'LH-OD201 Bi-Directional IP65 Outdoor Wall Lamp', isCover: true }],
    specifications: {
      dimensions: '100mm x 100mm x 100mm (Cube)',
      material: 'Marine-Grade Die-Cast Aluminum',
      finish: 'Textured Anodized Anthracite Grey',
      wattage: '12W Bridgelux COB LED (2 x 6W)',
      voltage: 'AC 85-265V 50/60Hz',
      colorTemperature: '3000K Warm White',
      ipRating: 'IP65 Waterproof',
      installationType: 'External Wall Surface Mount',
      beamAngle: 'Adjustable 0° - 120° Dual Beam',
      cri: 'Ra > 92',
      luminousFlux: '1100 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 19,
  },

  // ── 7. TABLE LAMP ─────────────────────────────────────────
  {
    catalogId: 'LH-CAT-020',
    name: 'LH-TL101 Marble Base Mushroom Table Lamp',
    slug: 'lh-tl101-marble-base-mushroom-table-lamp',
    sku: 'LH-TL101',
    category: 'table-lamp',
    subcategory: '',
    categoryName: 'Table Lamp',
    shortDescription: 'Italian Carrara marble base table lamp with spun brass domed reflector.',
    description: 'A striking sculptural centerpiece for nightstands, credenzas, and consoles. White Carrara marble pedestal supports a solid spun brass dome.',
    price: 4999,
    originalPrice: 6699,
    images: [{ url: '/categories/table-lamp.jpg', alt: 'LH-TL101 Marble Base Mushroom Table Lamp', isCover: true }],
    specifications: {
      dimensions: 'Dome Dia: 320mm, Height: 410mm, Base Dia: 140mm',
      material: 'Natural Carrara Marble & Spun Brass',
      finish: 'Honed Marble & Satin Brushed Brass',
      wattage: '2 x G9 LED 4W',
      voltage: 'AC 220-240V (Rotary Cord Dimmer)',
      colorTemperature: '2700K Warm Sunset Glow',
      ipRating: 'IP20',
      installationType: 'Tabletop Freestanding',
      beamAngle: 'Indirect Downward Mushroom Spread',
      cri: 'Ra > 95',
      luminousFlux: '700 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 20,
  },

  // ── 8. FLOOR LAMP ─────────────────────────────────────────
  {
    catalogId: 'LH-CAT-021',
    name: 'LH-FL101 Arched Brass Arc Floor Lamp',
    slug: 'lh-fl101-arched-brass-floor-lamp',
    sku: 'LH-FL101',
    category: 'floor-lamp',
    subcategory: '',
    categoryName: 'Floor Lamp',
    shortDescription: 'Dramatic cantilevered arch floor lamp with heavy black marble counterweight.',
    description: 'Extending a graceful brass arc over corner sofas and reading armchairs. Solid Nero Marquina marble counterweight ensures rock-solid stability.',
    price: 9800,
    originalPrice: 13200,
    images: [{ url: '/categories/floor-lamp.jpg', alt: 'LH-FL101 Arched Brass Arc Floor Lamp', isCover: true }],
    specifications: {
      dimensions: 'Total Height: 2100mm, Arc Reach: 1800mm, Base: 400mm Dia',
      material: 'Solid Brass Tubing & Heavy Nero Marble',
      finish: 'Brushed Golden Brass & Polished Black Marble',
      wattage: 'E27 Socket (Max 60W)',
      voltage: 'AC 220-240V',
      colorTemperature: 'Depends on Bulb',
      ipRating: 'IP20',
      installationType: 'Freestanding Floor Mount',
      beamAngle: 'Downlight Dome Wash',
      cri: 'Ra > 90',
      luminousFlux: '1100 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 21,
  },

  // ── 9. LED FILAMENT BULB ──────────────────────────────────
  {
    catalogId: 'LH-CAT-022',
    name: 'LH-FB101 ST64 Vintage Amber Spiral LED Filament Bulb',
    slug: 'lh-fb101-st64-amber-spiral-filament-bulb',
    sku: 'LH-FB101',
    category: 'led-filament-bulb',
    subcategory: '',
    categoryName: 'LED Filament Bulb',
    shortDescription: 'Teardrop Edison bulb with flexible curved spiral LED filament and amber glass.',
    description: 'Recreates the nostalgic vintage carbon-filament glow of 19th-century Edison lamps while consuming only 4W. Fits standard E27 pendant sockets.',
    price: 499,
    originalPrice: 699,
    images: [{ url: '/categories/led-filament-bulb.jpg', alt: 'LH-FB101 ST64 Vintage Amber Spiral LED Filament Bulb', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 64mm, Length: 142mm',
      material: 'Amber Tinted Glass & Brass Base',
      finish: 'Vintage Amber Glass',
      wattage: '4W (Equivalent to 40W Incandescent)',
      voltage: 'AC 220-240V 50Hz',
      colorTemperature: '2200K Golden Warm Glow',
      ipRating: 'IP20',
      installationType: 'E27 Screw Base',
      beamAngle: '360° Omnidirectional',
      cri: 'Ra > 95',
      luminousFlux: '350 Lumens',
    },
    isFeatured: true,
    isPublished: true,
    sortOrder: 22,
  },

  // ── 10. SPARE PART ────────────────────────────────────────
  {
    catalogId: 'LH-CAT-023',
    name: 'LH-SP101 Heavy-Duty Multi-Port Ceiling Canopy Hanging Base',
    slug: 'lh-sp101-multi-port-ceiling-canopy-hanging-base',
    sku: 'LH-SP101',
    category: 'spare-part',
    subcategory: 'hanging-base',
    categoryName: 'Spare Part',
    shortDescription: 'Reinforced circular ceiling canopy base with strain relief cord grip.',
    description: 'Premium metal canopy rose engineered for multi-pendant cluster configurations. Internal reinforced bracket supports up to 25kg fixture weight.',
    price: 1299,
    originalPrice: 1799,
    images: [{ url: '/categories/hanging-base.jpg', alt: 'LH-SP101 Heavy-Duty Multi-Port Ceiling Canopy Hanging Base', isCover: true }],
    specifications: {
      dimensions: 'Diameter: 300mm, Depth: 35mm',
      material: 'Thick-Gauge Pressed Carbon Steel',
      finish: 'Matte Jet Black / Brushed Brass Options',
      wattage: 'Rated up to 250V 16A',
      voltage: 'Universal AC Compatible',
      colorTemperature: 'N/A Hardware',
      ipRating: 'IP20',
      installationType: 'Ceiling Junction Box Mount',
      beamAngle: 'Hardware Accessory',
      cri: 'N/A',
      luminousFlux: 'Supports 25kg fixture weight',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 23,
  },
  {
    catalogId: 'LH-CAT-024',
    name: 'LH-SP201 Triac Dimmable Constant Current LED Driver 50W',
    slug: 'lh-sp201-triac-dimmable-led-driver-50w',
    sku: 'LH-SP201',
    category: 'spare-part',
    subcategory: 'spare-driver',
    categoryName: 'Spare Part',
    shortDescription: 'Flicker-free constant current replacement driver for luxury lighting.',
    description: 'High-performance replacement driver with built-in short circuit, over-voltage, and thermal overload protection. Supports leading/trailing edge Triac dimmers.',
    price: 1499,
    originalPrice: 1999,
    images: [{ url: '/categories/spare-driver.jpg', alt: 'LH-SP201 Triac Dimmable Constant Current LED Driver 50W', isCover: true }],
    specifications: {
      dimensions: '145mm x 48mm x 28mm',
      material: 'Flame-Retardant Polycarbonate Casing',
      finish: 'Matte Industrial Grey',
      wattage: '50W Max Output (700mA - 1200mA Adjustable)',
      voltage: 'Input: AC 200-240V, Output: DC 24-42V',
      colorTemperature: 'N/A Power Electronic',
      ipRating: 'IP20 Class II Double Insulated',
      installationType: 'In-Canopy / In-Cove Concealed',
      beamAngle: 'PF > 0.95 Flicker-Free',
      cri: 'N/A',
      luminousFlux: 'Efficiency > 88%',
    },
    isFeatured: false,
    isPublished: true,
    sortOrder: 24,
  },
];

export const seedCatalogItems = async () => {
  try {
    const count = await CatalogItem.countDocuments();
    if (count === 0) {
      console.log('[Catalog Seed] Seeding dedicated CatalogItem collection with unique IDs...');
      await CatalogItem.insertMany(INITIAL_CATALOG_ITEMS);
      console.log(`[Catalog Seed] ✅ Successfully seeded ${INITIAL_CATALOG_ITEMS.length} dedicated catalog items.`);
    } else {
      console.log(`[Catalog Seed] Catalog collection already has ${count} items. Synced.`);
    }
  } catch (err) {
    console.error('[Catalog Seed] Error seeding catalog items:', err);
  }
};
